# Generated by Django 2.1.5 on 2019-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100000, null=True),
        ),
    ]
