# Generated by Django 2.1.5 on 2019-01-30 16:27

from django.db import migrations
from django.utils import timezone

def create_category(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    names = ['Home', 'Gym', 'Work']

    for name in names:
        category = Category(name=name)
        category.save()

def delete_category(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.all().delete()

def create_task(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    Category = apps.get_model('api', 'Category')

    home_category_pk = Category.objects.get(name='Home').pk
    work_category_pk = Category.objects.get(name='Work').pk

    jobs = [
        {
            'title': 'Do dishes',
            'note': None,
            'starred': False,
            'start_date': timezone.now() - timezone.timedelta(hours=1),
            'end_date': timezone.now(),
            'category_id': home_category_pk
        },
        {
            'title': 'Work',
            'note': "It's important!",
            'starred': True,
            'start_date': timezone.datetime(2019, 1, 30, 8, 20),
            'end_date': timezone.datetime(2019, 1, 30, 8, 20) + timezone.timedelta(hours=2),
            'category_id': work_category_pk
        }
    ]

    for job in jobs:
        task = Task(
            title=job['title'],
            start_date=job['start_date'],
            end_date=job['end_date'],
            note=job['note'],
            starred=job['starred'],
            category_id=job['category_id']
        )
        task.save()

def delete_task(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    Task.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190130_0822'),
    ]

    operations = [
        migrations.RunPython(create_category, delete_category),
        migrations.RunPython(create_task, delete_task)
    ]
